config/routes.rb
Happy::Application.routes.draw do
    get 'signup' => 'users#new', :as => 'signup'
    get 'login' => 'sessions#new', :as => 'login'
    get 'logout' => 'sessions#destroy', :as => 'logout'

    resources :users
    resources :sessions

    resources :thoughts do
        get 'random', :on => :collection
    end

    resources :cheer_up, :path => '/cheer-up'

    root :to => 'home#index'

    # See how all your routes lay out with "rake routes"
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :thought
  attr_accessible :tag
end

app/models/thought.rb
class Thought < ActiveRecord::Base
    attr_accessible :thought, :created_at

    validates :thought,   :presence => true

    belongs_to :user
    has_many :tags

    before_save :create_tags

    def self.perspective(user_id, days_back)
        date = Date.today - days_back.days
        thought = Thought.where('user_id = ?', user_id).where('DATE(created_at) = ?', date)
    end

    protected

    def create_tags
        tags = self.thought.split(' ').select {|word| word.chars.first == '#'}

        for tag in tags do
            tag = tag.gsub(/[^A-Za-z]/, '')

            record = self.tags.find_or_create_by_tag(tag)

            record.save
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password

    attr_accessible :email, :password

    validates_presence_of :email
    validates_uniqueness_of :email

    def self.authenticate(email, password)
        find_by_email(email).try(:authenticate, password)
    end
end

app/models/users.rb
class Users < ActiveRecord::Base
    has_secure_password

    attr_accessible :email, :password

    validates_presence_of :email
    validates_uniqueness_of :email

    def self.authenticate(email, password)
        find_by_email(email).try(:authenticate, password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery

    helper_method :current_user

    private

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorized?
        unless session[:user_id]
            redirect_to login_path
        end
    end
end

app/controllers/cheer_up_controller.rb
class CheerUpController < ApplicationController
    before_filter :authorized?

    def index
        @tags = Tag.select('DISTINCT tag').joins(:thought).where('user_id = ?', current_user.id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.authenticate(params[:email], params[:password])
        if user
            session[:user_id] = user.id
            redirect_to thoughts_url
        else
            flash.now.alert = 'Invalid email or password'
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
    before_filter :authorized?

    # GET /thoughts
    # GET /thoughts.json
    def index
        @thought = Thought.new

        @perspective = []
        [7, 30, 365].each do |num|
            old_thought = Thought.perspective(current_user.id, num).first

            @perspective.push old_thought unless old_thought.nil?
        end

        respond_to do |format|
            format.html # index.html.erb
            format.json { render :json => @thoughts }
        end
    end

    # GET /thoughts/1
    # GET /thoughts/1.json
    def show
        @thought = Thought.find(params[:id])

        respond_to do |format|
            format.html # show.html.erb
            format.json { render :json => @thought }
        end
    end

    # GET /thoughts/new
    # GET /thoughts/new.json
    def new
        @thought = Thought.new

        respond_to do |format|
            format.html # new.html.erb
            format.json { render :json => @thought }
        end
    end

    # GET /thoughts/1/edit
    def edit
        @thought = Thought.find(params[:id])
    end

    # POST /thoughts
    # POST /thoughts.json
    def create
        @thought = Thought.new(params[:thought])
        @thought.user_id = current_user.id

        respond_to do |format|
            if @thought.save
                format.html { redirect_to @thought, :notice => 'Thought was successfully created.' }
                format.json { render :json => @thought, :status => :created, :location => @thought }
            else
                format.html { render :action => "new" }
                format.json { render :json => @thought.errors, :status => :unprocessable_entity }
            end
        end
    end

    # PUT /thoughts/1
    # PUT /thoughts/1.json
    def update
        @thought = Thought.find(params[:id])

        respond_to do |format|
            if @thought.update_attributes(params[:thought])
                format.html { redirect_to @thought, :notice => 'Thought was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render :action => "edit" }
                format.json { render :json => @thought.errors, :status => :unprocessable_entity }
            end
        end
    end

    # DELETE /thoughts/1
    # DELETE /thoughts/1.json
    def destroy
        @thought = Thought.find(params[:id])
        @thought.destroy

        respond_to do |format|
            format.html { redirect_to thoughts_url }
            format.json { head :no_content }
        end
    end

    def random
        if params.has_key?(:tag)
            thoughts = Thought.joins(:tags).where('user_id = ?', current_user.id).where('tag = ?', params[:tag]).order("RANDOM()").limit(1)
        else
            thoughts = Thought.where('user_id = ?', current_user.id).order("RANDOM()").limit(1)
        end

        @thought = thoughts.first

        respond_to do |format|
            format.html { render :template => 'thoughts/show.html.erb' }
            format.json { render :json => @thought }
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def create
      @user = User.new(params[:user])
      if @user.save
          session[:user_id] = @user.id
          redirect_to thoughts_path
      else
          render 'new'
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheer_up_helper.rb
module CheerUpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheer_up/_form.html.erb
<%= form_tag({:controller => 'thoughts', :action => 'random'}, :method => 'get') do %>
    <%= submit_tag 'Cheer Up', :class => 'btn btn-primar btn-large' %>
<% end %>

app/views/cheer_up/index.html.erb
<section class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <p>Looking for a specific thought to feel better?</p>
                <li class="nav-header">Thought Keywords</li>
                <ul>
                <% @tags.each do |tag| %>
                    <li><%= link_to tag.tag, random_thoughts_path(:tag => tag.tag) %></li>
                <% end %>
                </ul>
            </div>
        </div>
        <div class="span9">
            <div>
                <h1>Cheer Up!</h1>
                <p>Feeling down? Look at one of the random happy thoughts you recorded and start to feel better.</p>
            
                <%= render 'form' %>
            </div>
        </div>
    </div>
</section>

app/views/home/index.html.erb
<section class="container">
    <div class="hero-unit">
        <h1>Happy App <small>beta</small></h1>
        <p>Write down happy thoughts so you can refer to them later. Think of this a micro-diary; all thoughts are private.</p>
    
        <%= link_to "Write down a happy thought", signup_path, :class => 'btn' %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Happy</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

    <header class="container">
        <div class="navbar">
            <div class="navbar-inner">
                <%= link_to 'Happy App', root_path, :class => 'brand' %>
                <ul class="nav">
                    <li><%= link_to 'Thoughts', thoughts_path %></li>
                    <li><%= link_to 'Cheer Me Up!', cheer_up_index_path %></li>
                </ul>
                <% if current_user %>
                    <ul class="nav pull-right">
                        <li><%= link_to 'Logout', logout_path %></li>
                    </ul>
                    <p class="navbar-text pull-right">Hi, <%= current_user.email %></p>
                <% else %>
                    <ul class="nav pull-right">
                        <li><%= link_to 'Signup', signup_path %></li>
                        <li><%= link_to 'Login', login_path %></li>
                    </ul>
                <% end %>
            </div>
        </div>
    </header>
    <%= yield %>

</body>
</html>

app/views/thoughts/_form.html.erb
<%= form_for(@thought) do |f| %>
  <% if @thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
      <% @thought.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thought, 'Write down a happy thought!' %><br />
    <%= f.text_area :thought %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing thought</h1>

<%= render 'form' %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<div class="container" id="thought">
    <%= render 'form' %>

    <% if @perspective.length %>
        <div id="perspective">
            <ul class="unstyled">
                <% @perspective.each do |p| %>
                    <li><%= link_to (Date.today - p.created_at.to_date).to_i.to_s + ' days ago', p%> you wrote: <em><%= p.thought %></em></li>
                <% end %>
            </ul>
        </div>
    <% end %>
</div>

app/views/thoughts/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<section class="container well thought">
    <p class="thought-text"><%= @thought.thought %></p>
    <p class="thought-date pull-left">Written at <%= @thought.created_at.strftime '%l:%M %P' %> on <%= @thought.created_at.strftime '%b %-d %Y' %></p>
    <p class="thought-edit pull-right"><%= link_to 'Edit', edit_thought_path(@thought) %></p>
</section>

app/views/users/new.html.erb
<div class="container" id="user">
    <h1>Signup</h1>
    
    <%= form_for(@user) do |f| %>
    
        <div class="field">
            <%= f.label :email, 'Email' %>
            <%= f.text_field :email %>
        </div>
    
        <div class="field">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password %>
        </div>
    
        <div class="actions">
            <%= f.submit 'Signup' %>
        </div>
    <% end %>
</div>